version: 2.1
jobs:
   test:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run: mvn test       
   package:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run: mvn package
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package