version: 2.1
jobs:
   test:
      docker:
        - image: circleci/openjdk:8-jdk
      working_directory: ~/test
      steps:
        - checkout
        - run:
            name: run test 
            command: mvn test 
        - save_cache:
            key: test-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/test

   package:
      docker:
        - image: circleci/openjdk:8-jdk
      working_directory: ~/test
      steps:
        - restore_cache:
            key: test-{{ .Environment.CIRCLE_SHA1 }}
        - run: 
            name: package
            command: mvn package
        - save_cache:
            key: test123-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/test

   show_env:
      docker:
        - image: circleci/openjdk:8-jdk
      working_directory: ~/test
      steps:
      - restore_cache:
          key: test123-{{ .Environment.CIRCLE_SHA1 }}
      -run:
        name: ls -la
        command: ls -la



workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
         requires:
          - test
      - show_env:
          requires:
            - package