version: 2.0
jobs:
   build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn test 
    test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn package
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test