version: 2.1
jobs:
   test:
      docker:
        - image: circleci/openjdk:8-jdk
      working_directory: ~/test
      steps:
        - checkout
        - run:
            name: run test 
            command: mvn test 
        - save_cache:
            key: test
            paths:
              - ~/test

   package:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run: 
            name: package
            command: mvn package
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package